name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run unit tests
        run: |
          pytest --cov=. --cov-report=xml --cov-report=term -k "not integration"
        env:
          AZURE_MAPS_KEY: dummy_key_for_testing
          
      - name: Run integration tests
        run: |
          pytest -v -m integration
        env:
          AZURE_MAPS_KEY: ${{ secrets.AZURE_MAPS_KEY }}
        continue-on-error: true
          
      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          fail_ci_if_error: false